- hosts: webserver
  vars:
          - port: "8080"
  tasks:
          - name: "installing httpd"
            package: 
                name: "httpd"
                state: present

          - name: "creating directory"
            file:
                path: "/var/www/akash"
                state: directory
          - name: "copying config file"
            template: 
                src: "new.conf"
                dest: "/etc/httpd/conf.d/new.conf"
            notify: "restarting httpd"

          - name: "creating web page"
            copy:
                content: "configuring handlers"
                dest: "/var/www/akash/index.html"
          - name: "starting services"
            service:
                name: "httpd"
                state: started   


  handlers:
   - name: "restarting httpd"
     service:
             name: "httpd"
             state: restarted  
